### PR TITLE
Added Logo

### PR DESCRIPTION
**Pull request by rmtngh**

### CODE REVIEW

**Comment by mike442144** [comment]
Wow, that's awesome ,  I didn't see your pull request and just upload the logo last day. so what do you think of the two logos

**Comment by mike442144** [comment]
What do you think of using this logo in our another project [node-ds](https://github.com/bda-research/node-ds), with some modifications.

**Comment by mike442144** [comment]
@BrightSkyz Actually, this project is not a 'spider', but like a 'scrapper'. But it's a good logo, I think we can use it in our `node-ds` repo by replacing the 'spider'

**Comment by BrightSkyz** [comment]
@mike442144 It crawls over things looking for data. That's my thought -- also, it could be used as a spider.

**Pull request closed without merging**
